server:
  port: 9083

spring:
  profiles:
    active: prod
    include: website,alipay,oss

jwt:
  secret: novel!#20191230
  expiration: 604800

#缓存管理密码
cache:
  manager:
    password: novel@2020117


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接 （多个用逗号分隔）
  urlPatterns: /book/addCommentReply,/book/addBookComment,/user/addFeedBack,/author/addBook,/author/addBookContent,/author/updateBookContent,/author/register.html


author:
  income:
    #税率(扣税后所得比率)
    tax-rate: 0.9
    #分佣比例
    share-proportion: 0.7
    #兑换比率(人民币)
    exchange-proportion: 0.01

#小说章节定价规则
book:
  price:
    #字数
    word-count: 1000
    #价值(屋币)
    value: 5


--- #--------------------- Spring AI 配置----------------------
spring:
  ai:
    # ================== Chroma 向量库连接配置（重点！） ==================
    vectorstore:
      chroma:
#        base-url: http://192.168.31.2:8000
        client:
          host: http://192.168.31.2     # ← 必须改成 Mac Mini 的真实 IP（不是 localhost！）
          port: 8000                           # Chroma HTTP Server 端口
        # 可选配置
        collection-name: novels                # 跟你 Python 脚本里用的 collection 名保持一致（默认是 "SpringAiCollection"）
        initialize-schema: false               # 你的向量库已经建好，关闭自动建表
        tenantName: default_tenant
        databaseName: default_database
    ollama:
      base-url: http://192.168.31.13:11434
      embedding:
        model: bge-m3
    openai:
      image:
        enabled: true
        base-url: https://api.siliconflow.cn
        api-key: sk-jjtixmivxaccndqgkqfkbgkzvmbctdxogcrfbjzfttbouitt
        options:
          model: Kwai-Kolors/Kolors
          response_format: URL
      api-key: sk-jjtixmivxaccndqgkqfkbgkzvmbctdxogcrfbjzfttbouitt
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    mcp:
      server:
        enabled: true
        protocol: STREAMABLE
        type: SYNC
        name: book_mcp_server
        version: 1.0.0
        endpoint: /mcp
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
    # ================== 嵌入模型配置（bge-m3） ==================
    embedding:
      model:
        ollama:
          base-url: http://192.168.31.13:11434     # 或你的 Ollama 地址
          model-name: bge-m3                   # 和你索引时用的完全一致

