java2nb:
  uploadPath: /var/pic/
  username: admin
  password: 111111
logging:
  level:
    root: error
    com.java2nb: error
spring:
  redis:
    host: 192.168.31.2
    port: 6379
    password: 1234
    # 连接超时时间（毫秒）
    timeout: 10000


