java2nb:
  uploadPath: /var/pic/
  username: admin
  password: 111111
logging:
  level:
    root: info
    com.java2nb: debug
spring:
  redis:
    host: www.tbc.pub
    port: 19736
    password: 1234
    # 连接超时时间（毫秒）
    timeout: 10000
  datasource:
    driverClassName: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:absolutepath:${user.dir}/config/shardingsphere-jdbc-dev.yml

