java2nb:
  uploadPath: /var/pic/
  username: admin
  password: 111111
logging:
  level:
    root: error
    com.java2nb: error
spring:
  redis:
    host: www.tbc.pub
    port: 19736
    password: 1234
    # 连接超时时间（毫秒）
    timeout: 10000


